jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: echo "build"
  test1:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: echo "test1"
  test2:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: echo "test2"
  test3:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: echo "test3"
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run: echo "deploy"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - test3:
          requires:
            - test1
      - deploy:
          requires:
            - test2
